### ISSUE TITLE
Unable to find the created zim file

### ISSUE THREAD

**Issue by Sudarshan-21** [openzim/kolibri#110]
I created a .zim file using a kobibri channel, but I am unable to locate the .zim file on my machine.
![Screenshot from 2024-03-13 14-43-54](https://github.com/openzim/kolibri/assets/137636943/4c6bf2e1-8cf5-47c4-b97f-ece9d2adcce8)
![Screenshot from 2024-03-13 14-51-59](https://github.com/openzim/kolibri/assets/137636943/67851438-9699-49d7-94ca-a6bed4f59507)

referring to the screenshot, I guess I have successfully created the aim file, can somebody please help me loate the .zim file also please guide me on what localhost or url are these html pages are rendering to(ie. HTML pages in this repository). Please correct my question if I am missing on to sometings or having any misunderstanding.
@rgaudin

**Comment by kelson42** [comment]
Would be great to have the log telling which ZIM file(s) have been created and where... even if in the context of a container this information can not be directly usable.

**Comment by benoit74** [comment]
You already have valuable information in the log :
- build_dir: where temporary files are stored (probably the HTML you are referring to are here, even if I'm not sure)
- output: where the ZIMs are produced

In your case the output is `/output` (inside the container), and you mapped/mounted this directory in a docker volume named `my_dir`. If you want the ZIM to survive the container and be directly accessible on your machine, you should probably mount a directory instead of a docker volume which are way harder to explore.

**Comment by Sudarshan-21** [comment]
first problem is sorted, I found the .zim file 😇
![Screenshot from 2024-03-14 22-25-16](https://github.com/openzim/kolibri/assets/137636943/0758c0c1-83cb-4ae6-8677-f5827f0ba252)

Now I might be dumb asking this, but still... the second question is about The HTML files (to be precise, the base.html file and others)...... As far as I am able to understand, they are fetching details()title, description, logo, etc) from the channel of which we are providing the ID of......... Now, the question is, on what url will I find the HTML files (base.html and others) getting displayed......or is it like I need to run kiwix-desktop and then run that created .zim file on it ?

![Screenshot from 2024-03-14 22-42-38](https://github.com/openzim/kolibri/assets/137636943/5e2ac65e-e3e4-4dfe-91b2-e97a1176c231)

**Comment by benoit74** [comment]
ZIM file have to be opened with a ZIM reader to have access to files inside the archive.

**Comment by Sudarshan-21** [comment]
Thanks a lot, got everything working....
