### ISSUE TITLE
Better UI: Do we want to force consistent cards size?

### ISSUE THREAD

**Issue by Sudarshan-21** [openzim/kolibri#117]
![Screenshot from 2024-03-27 23-17-53](https://github.com/openzim/kolibri/assets/137636943/35540f99-d2fc-493e-a66d-4e6dd1c71ac6)

the cards size is inconsistent as shown in the above image

**Comment by benoit74** [comment]
The card sizes are inconsistent because the image sizes in Kolibri Channel are inconsistent. Cropping them or adding blank areas around them to force one single size is not going to necessarily be more elegant. I consider that it is the responsibility of the Channel creator to ensure consistent thumbnail sizes in a given topic.

To be discussed / decided.

**Comment by Sudarshan-21** [comment]
![Screenshot from 2024-03-28 17-30-24](https://github.com/openzim/kolibri/assets/137636943/1102a3c5-0884-4c06-9a50-625aa117bc9e)

if the card text and open button is settled to bottom, and the width is made consistent, the idea is worth thinking about taking into consideration.
if @benoit74 agrees, I would like to work on this

**Comment by benoit74** [comment]
> if the card text and open button is settled to bottom, and the width is made consistent, the idea is worth thinking about taking into consideration.

the width => the height ?

I'm anyway open to PRs on that issue. 

I'm just not sure of the result on items like the ones of your first screenshot, so I'm a bit afraid the effort might not be worth it. But anyway it is probably worth a try.

Especially since you are totally right that button should be settled to bottom

I'm not sure about the text (if image height is constant, then the text is maybe better at the top - of the bottom area ...)

**Comment by Sudarshan-21** [comment]
> > if the card text and open button is settled to bottom, and the width is made consistent, the idea is worth thinking about taking into consideration.
> 
> the width => the height ?
> 
> I'm anyway open to PRs on that issue.
> 
> I'm just not sure of the result on items like the ones of your first screenshot, so I'm a bit afraid the effort might not be worth it. But anyway it is probably worth a try.
> 
> Especially since you are totally right that button should be settled to bottom
> 
> I'm not sure about the text (if image height is constant, then the text is maybe better at the top - of the bottom area ...)

Nah, I fixed the height but messed up the width of a card.
I am proposing to achieve the following proposed design, I guess it is quite satisfactory

![WhatsApp Image 2024-03-28 at 7 36 17 PM](https://github.com/openzim/kolibri/assets/137636943/dfbc3d3a-2113-440f-953d-eadabd5bc33e)

**Comment by benoit74** [comment]
I'm not sure about your new design. Colors seems ... too colorful. And I don't get what the "Request a demo" means.

This is a significant change which will lead to many discussions.

I suggest to stay focus on:
- fixing the image height (meaning that images will have to be fitted inside the available area or cropped)
- settling the button to the bottom

And please experiment with image from the minimal test channel, these are the kind of images we encounter "in the wild".

**Comment by Sudarshan-21** [comment]
Those colors are for sure going to be replaced by the images.
"Request a demo" is just a placeholder, nothing i am going to address at the time

as you say, I will try to focus on 1) maintaining consistent card height 
                                                   2)settling the button to bottom
                                                   3)(will give a try to) maintain same image size

**Comment by benoit74** [comment]
Perfect then!
