### ISSUE TITLE
Better UI: tag filtering

### ISSUE THREAD

**Issue by benoit74** [openzim/kolibri#60]
This is a subtask of https://github.com/openzim/kolibri/issues/42

Setup "tag filtering" as in Endless UI (e.g https://key.endlessos.org/en/explore/#/topics/c9d7f950ab6b5a1199e3d6c10d7f0103).

<img width="650" alt="Endless UI copy" src="https://github.com/openzim/kolibri/assets/7102089/e7b63adc-c33c-4699-95d7-2f866842a672">
﻿

**Comment by githyuvi** [comment]
@benoit74 Need few suggestions before working on this.
Topic count is less in this example. But for some zims, take African Storybook for example, there are more than 150 topics in home page. That would take too much area
1. **Toolbar/Tagbar Space Limitation**: Default limit to the space allocated for displaying tags
2. **Expand Button Option**: Reveals additional topics/tags, maybe a drop-down menu 
3. **Limit tag size**: So that long topics names does not disrupt the layout.
4. **Fixed Toolbar Size with Overflow Handling**: Alternative to second solution.

**Comment by githyuvi** [comment]
https://github.com/openzim/kolibri/assets/96630446/c19e811e-b6a7-499e-bfb0-14d1ee9c1704

This is how it would look without implementing the issues I mentioned above. Plus the video includes both topic and non topic tags

**Comment by benoit74** [comment]
I propose to:
- limit the tag width ; overflow text replaced by emphasis ; on hover, a tooltip displays the whole tag
- limit the number of tags displayed (ideally two or three rows - I let you decide - but maybe easier to limit to a given number of tags instead of number of rows, to not have to compute - complex with responsiveness - on which row a given tag would be displayed)
- expand button to display all tags is a very good idea (e.g. "More ..." button)
- only topics are included as tags (like Endless does), not other kind of nodes

**Comment by githyuvi** [comment]
@benoit74 One more thing. Endless has topic tags only in home page. But I think it's useful to have in every topic page. What do you say?

**Comment by githyuvi** [comment]
@benoit74 Please review this new feature and let me know any enhancements.
